-- 0013_certificates.sql
--
-- Sprint 16: certificate generation.
--   - `certificate_templates` holds reusable branding/copy per workspace;
--     `is_default` marks the one used when an experience has no explicit
--     `certificate_template_id` set on its completion criteria.
--   - `experience_completion_criteria` is one row per experience (unique on
--     experience_id) describing what "eligible for a certificate" means for
--     that experience. `auto_issue` drives a best-effort hook from check-in
--     and survey submission — see features/certificates/actions.ts.
--   - `certificates` snapshots participant_name/experience_title/
--     organization_name at issue time so a certificate stays accurate even
--     if the participant, experience, or client record changes later.
--     `verification_code` is generated by Postgres, never in application
--     code, and is what the public /verify/[code] page looks up.
--   - The partial unique index on (participant_id, experience_id) where
--     revoked_at is null means a participant can be issued a fresh
--     certificate after a prior one is revoked, but never two live ones for
--     the same experience.
--
-- Run manually via the Supabase SQL editor. Safe to re-run.

create table if not exists certificate_templates (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspaces(id),
  name text not null,
  -- Branding
  organization_name text not null,
  organization_logo_url text,
  primary_color text not null default '#C9A96E',
  secondary_color text not null default '#26215C',
  background_color text not null default '#FFFFFF',
  font_family text not null default 'serif',
  -- Content
  title_text text not null default 'Certificate of Completion',
  body_text text not null default 'This is to certify that',
  footer_text text,
  signatory_name text,
  signatory_title text,
  -- Meta
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists experience_completion_criteria (
  id uuid primary key default gen_random_uuid(),
  experience_id uuid not null references experiences(id) on delete cascade,
  require_attendance boolean not null default true,
  require_survey_completion boolean not null default false,
  minimum_attendance_percentage integer not null default 100
    check (minimum_attendance_percentage between 1 and 100),
  certificate_template_id uuid references certificate_templates(id),
  auto_issue boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(experience_id)
);

create table if not exists certificates (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspaces(id),
  participant_id uuid not null references participants(id),
  experience_id uuid not null references experiences(id),
  template_id uuid references certificate_templates(id),
  -- Certificate content snapshot (immutable at time of issue)
  participant_name text not null,
  experience_title text not null,
  organization_name text not null,
  completion_date date not null,
  -- Delivery
  verification_code text not null unique
    default upper(substring(replace(gen_random_uuid()::text, '-', ''), 1, 12)),
  issued_at timestamptz not null default now(),
  emailed_at timestamptz,
  email_address text not null,
  -- Status
  revoked_at timestamptz,
  revocation_reason text,
  created_at timestamptz not null default now()
);

create index if not exists certificates_participant_id_idx on certificates(participant_id);
create index if not exists certificates_experience_id_idx on certificates(experience_id);
create index if not exists certificates_verification_code_idx on certificates(verification_code);
create unique index if not exists certificates_participant_experience_live_idx
  on certificates(participant_id, experience_id)
  where revoked_at is null;

alter table certificate_templates enable row level security;
alter table experience_completion_criteria enable row level security;
alter table certificates enable row level security;

drop policy if exists "Authenticated users can manage certificate templates" on certificate_templates;
create policy "Authenticated users can manage certificate templates"
  on certificate_templates for all to authenticated using (true);

drop policy if exists "Authenticated users can manage completion criteria" on experience_completion_criteria;
create policy "Authenticated users can manage completion criteria"
  on experience_completion_criteria for all to authenticated using (true);

drop policy if exists "Authenticated users can manage certificates" on certificates;
create policy "Authenticated users can manage certificates"
  on certificates for all to authenticated using (true);

drop policy if exists "Public can verify certificates" on certificates;
create policy "Public can verify certificates"
  on certificates for select to anon
  using (revoked_at is null);

drop trigger if exists certificate_templates_updated_at on certificate_templates;
create trigger certificate_templates_updated_at
  before update on certificate_templates
  for each row execute function update_updated_at();

-- Seed a default template for the Enable My Growth workspace (guarded by
-- `not exists` rather than `on conflict`, since there's no unique
-- constraint to target — this keeps a re-run from inserting duplicates).
insert into certificate_templates (
  workspace_id, name, organization_name,
  primary_color, secondary_color, background_color,
  title_text, body_text, footer_text,
  signatory_name, signatory_title, is_default
)
select
  w.id,
  'Default Template',
  'Enable My Growth',
  '#C9A96E', '#26215C', '#FFFFFF',
  'Certificate of Completion',
  'This is to certify that',
  'Enable My Growth · enablemygrowth.com',
  'Feras Banna',
  'Founder, Enable My Growth',
  true
from workspaces w
join organizations o on o.id = w.organization_id
where o.slug = 'enable-my-growth'
  and not exists (
    select 1 from certificate_templates ct where ct.workspace_id = w.id
  )
limit 1;
